# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('ni', models.BigAutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=32, unique=True, verbose_name='SN号')),
                ('type', models.IntegerField(choices=[(1, '笔记本'), (2, '台式机'), (3, '显示器')], verbose_name='类型')),
                ('status', models.IntegerField(choices=[(1, '使用'), (2, '未使用')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '固定资产',
                'verbose_name_plural': '固定资产',
            },
        ),
        migrations.CreateModel(
            name='asset_model',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='型号')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='姓名')),
                ('computer', models.IntegerField(choices=[(1, '博莹'), (2, '信产所')], verbose_name='类型')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_model',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.asset_model', verbose_name='型号'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Member', verbose_name='使用人'),
        ),
    ]
