# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='asset',
            name='macaddress',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MAC地址'),
        ),
    ]
