# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_auto_20170918_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_model',
            field=models.ForeignKey(max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.asset_model', verbose_name='型号'),
        ),
    ]
