# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='服务器名')),
                ('ext_ip', models.GenericIPAddressField()),
                ('int_ip', models.GenericIPAddressField()),
                ('status', models.IntegerField(choices=[(1, '使用'), (2, '未使用'), (3, '下线')])),
            ],
            options={
                'verbose_name_plural': '基础表',
                'verbose_name': '基础表',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=32, verbose_name='项目名')),
                ('servidor', models.ManyToManyField(to='base.Base')),
            ],
            options={
                'verbose_name_plural': '项目表',
                'verbose_name': '项目表',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=32, verbose_name='服务名')),
                ('entorno', models.CharField(choices=[('uat', '测试环境'), ('prd', '生产环节'), ('demo', '演示环境')], max_length=8, verbose_name='环境')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('is_jar_or_war', models.CharField(choices=[(1, '是'), (2, '否')], max_length=2, verbose_name='是否jar或者war')),
                ('jar', models.CharField(blank=True, max_length=32, null=True, verbose_name='java包名')),
                ('start_user', models.CharField(max_length=8, verbose_name='启动用户')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Base')),
            ],
            options={
                'verbose_name_plural': '服务表',
                'verbose_name': '服务表',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
