# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='servidor',
        ),
        migrations.AddField(
            model_name='project',
            name='servidor',
            field=models.ManyToManyField(to='base.Base'),
        ),
    ]
